### ISSUE TITLE
Downloaded today this game and i really like it :)!!!!!

### ISSUE THREAD

**Issue by goxr3plus** [Marcoral/Matching-Game#1]
Downloaded today this game and i really like it :)!!!!!

**Comment by goxr3plus** [comment]
It's a good practice to add a read me with images from your game because it is really nice . And how to download and stuff . All the github repositories must have a read me.

How to add images .

One technique i use i going on releases section => starting a new release => drag and drop an image on the description of release so it get's uploaded on github => discard the release and copy the link from the uploaded image.

You can do the same here on issues , drag and drop an image in your comment and it will get uploaded , get the link and paste in on readme VOILA :)

**Comment by Marcoral** [comment]
I'm glad you liked the game!
I created it in a little rush as it was my academic project with a deadline of a week.

I'm also grateful for your advice. I added readme file which you requested! VOILA :)
Nice image trick btw
